import React from 'react';
import { View, Text, ScrollView, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import BottomNav from '../components/BottomNav';
import { useTheme } from '../../theme/ThemeContext';
import type { NavTab } from '../types';

export default function AnalyticsScreen({ activeTab, onTabPress }: { activeTab: NavTab; onTabPress: (tab: NavTab) => void }) {
  const { theme } = useTheme();
  const bars = [42, 58, 51, 76, 68, 84, 73];
  return <SafeAreaView style={[styles.root, { backgroundColor: theme.background }]} edges={['top']}><ScrollView contentContainerStyle={styles.content}><Text style={[styles.eyebrow, { color: theme.accentSecondary }]}>PERFORMANCE</Text><Text style={[styles.title, { color: theme.textPrimary }]}>Analytics</Text><View style={styles.cards}>{[['74%', 'Fleet utilization'], ['₹68', 'Cost per delivery'], ['128', 'Orders this week']].map(([value, label]) => <View key={label} style={[styles.card, { backgroundColor: theme.card, borderColor: theme.border }]}><Text style={[styles.value, { color: theme.accentPositive }]}>{value}</Text><Text style={[styles.label, { color: theme.textSecondary }]}>{label}</Text></View>)}</View><View style={[styles.chartCard, { backgroundColor: theme.card, borderColor: theme.border }]}><Text style={[styles.chartTitle, { color: theme.textPrimary }]}>Order volume</Text><View style={styles.chart}>{bars.map((height, index) => <View key={index} style={styles.barTrack}><View style={[styles.bar, { height: `${height}%`, backgroundColor: index === bars.length - 1 ? theme.accentPositive : theme.accentSecondary }]} /></View>)}</View><View style={styles.days}>{['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((day, index) => <Text key={index} style={[styles.day, { color: theme.textSecondary }]}>{day}</Text>)}</View></View><View style={[styles.insight, { borderColor: theme.border }]}><Text style={[styles.insightTitle, { color: theme.textPrimary }]}>Routing insight</Text><Text style={[styles.insightText, { color: theme.textSecondary }]}>Kiosk-assisted routes protect delivery completion when battery drops below the safety buffer.</Text></View></ScrollView><BottomNav activeTab={activeTab} onTabPress={onTabPress} /></SafeAreaView>;
}
const styles = StyleSheet.create({ root: { flex: 1 }, content: { padding: 20, paddingBottom: 28 }, eyebrow: { fontSize: 10, fontWeight: '800', letterSpacing: 1.4 }, title: { fontSize: 28, fontWeight: '800', marginTop: 3, marginBottom: 20 }, cards: { flexDirection: 'row', gap: 8, marginBottom: 18 }, card: { flex: 1, borderWidth: 1, borderRadius: 15, padding: 11 }, value: { fontSize: 20, fontWeight: '800' }, label: { fontSize: 10, marginTop: 4, lineHeight: 14 }, chartCard: { borderWidth: 1, borderRadius: 18, padding: 16, marginBottom: 16 }, chartTitle: { fontSize: 15, fontWeight: '800', marginBottom: 18 }, chart: { height: 150, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-around', gap: 10 }, barTrack: { height: '100%', flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(128,128,128,0.08)', borderRadius: 5 }, bar: { width: '100%', borderRadius: 5 }, days: { flexDirection: 'row', justifyContent: 'space-around', marginTop: 8 }, day: { fontSize: 10 }, insight: { borderWidth: 1, borderRadius: 16, padding: 15 }, insightTitle: { fontSize: 14, fontWeight: '800', marginBottom: 5 }, insightText: { fontSize: 12, lineHeight: 18 } });
