import React from 'react';
import { View, Text, ScrollView, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import BottomNav from '../components/BottomNav';
import { orders } from '../data';
import { useTheme } from '../../theme/ThemeContext';
import type { NavTab } from '../types';

const swaps = [
  { vehicleId: 'V-04', stationName: 'BaaS Kiosk - Katpadi Rd', timestamp: 'Today, 10:42 AM', durationMinutes: 8 },
  { vehicleId: 'V-06', stationName: 'BaaS Kiosk - Gandhi Nagar', timestamp: 'Yesterday, 4:18 PM', durationMinutes: 11 },
];
export default function HistoryScreen({ activeTab, onTabPress }: { activeTab: NavTab; onTabPress: (tab: NavTab) => void }) {
  const { theme } = useTheme();
  return <SafeAreaView style={[styles.root, { backgroundColor: theme.background }]} edges={['top']}><ScrollView contentContainerStyle={styles.content}><Text style={[styles.eyebrow, { color: theme.accentSecondary }]}>ACTIVITY</Text><Text style={[styles.title, { color: theme.textPrimary }]}>History</Text><View style={styles.chips}><View style={[styles.chip, { backgroundColor: theme.card, borderColor: theme.border }]}><Text style={[styles.chipValue, { color: theme.accentPositive }]}>42</Text><Text style={[styles.chipLabel, { color: theme.textSecondary }]}>Deliveries Today</Text></View><View style={[styles.chip, { backgroundColor: theme.card, borderColor: theme.border }]}><Text style={[styles.chipValue, { color: theme.accentCaution }]}>3</Text><Text style={[styles.chipLabel, { color: theme.textSecondary }]}>Swaps Triggered</Text></View></View><Text style={[styles.section, { color: theme.textPrimary }]}>Completed Deliveries</Text><View style={styles.list}>{orders.filter((order) => order.status === 'Picked Up' || order.status === 'Assigned').map((order) => <View key={order.id} style={[styles.row, { backgroundColor: theme.card, borderColor: theme.border }]}><View style={styles.rowMain}><Text style={[styles.id, { color: theme.textPrimary }]}>{order.id}</Text><Text style={[styles.route, { color: theme.textSecondary }]}>{order.pickup} to {order.drop}</Text><Text style={[styles.meta, { color: theme.textSecondary }]}>{order.distance} · 32 min</Text></View><Text style={[styles.payout, { color: theme.accentPositive }]}>{order.payout}</Text></View>)}</View><Text style={[styles.section, { color: theme.textPrimary }]}>Battery Swap History</Text><View style={styles.list}>{swaps.map((swap) => <View key={`${swap.vehicleId}-${swap.timestamp}`} style={[styles.row, { backgroundColor: theme.card, borderColor: theme.border }]}><View style={styles.rowMain}><Text style={[styles.id, { color: theme.textPrimary }]}>{swap.vehicleId} · {swap.stationName}</Text><Text style={[styles.route, { color: theme.textSecondary }]}>{swap.timestamp}</Text></View><Text style={[styles.meta, { color: theme.textSecondary }]}>{swap.durationMinutes} min</Text></View>)}</View></ScrollView><BottomNav activeTab={activeTab} onTabPress={onTabPress} /></SafeAreaView>;
}
const styles = StyleSheet.create({ root: { flex: 1 }, content: { padding: 20, paddingBottom: 28 }, eyebrow: { fontSize: 10, fontWeight: '800', letterSpacing: 1.4 }, title: { fontSize: 28, fontWeight: '800', marginTop: 3, marginBottom: 20 }, chips: { flexDirection: 'row', gap: 10, marginBottom: 22 }, chip: { flex: 1, borderWidth: 1, borderRadius: 16, padding: 14 }, chipValue: { fontSize: 24, fontWeight: '800' }, chipLabel: { fontSize: 10, marginTop: 4 }, section: { fontSize: 18, fontWeight: '800', marginBottom: 10 }, list: { gap: 8, marginBottom: 24 }, row: { borderWidth: 1, borderRadius: 15, padding: 13, flexDirection: 'row', alignItems: 'center' }, rowMain: { flex: 1, gap: 4 }, id: { fontSize: 12, fontWeight: '800' }, route: { fontSize: 11 }, meta: { fontSize: 10 }, payout: { fontSize: 14, fontWeight: '800' } });
